#!/bin/sh

# This script makes a dmenu promt for mounting drives.

term='st -f monospace:size=16'

pgrep -x dmenu && exit

mountable=$( lsblk -lp | grep "part $" | awk '{print $1, "(" $4 ")"}')
[[ "$mountable" = "" ]] && exit 1
chosen=$(echo "$mountable" | dmenu -i -p "Which drive to mount?" | awk '{print $1}')
[[ "$chosen" = "" ]] && exit 1
$term sudo mount $chosen && exit 0

dir=$(find /mnt -type d -maxdepth 3 2>/dev/null)
mountpoint=$(echo "$dir" | dmenu -i -p "Select mount point:" )
[[ "$mountpoint" = "" ]] && exit 1

sudo mount $chosen $mountpoint
