# Uncomment to load xresources file

slstatus &

# Uncomment and edit to set the wallpaper.
feh --bg-fill ~/Pictures/Mountains.jpg

# Uncomment to load the compositing manager with X.
xcompmgr &

# Hide mouse cursor after 3 seconds of inactivity
unclutter -idle 3 &
xrdb ~/.Xresources &
# Saving a dwm log
exec dwm > ~/.dwm.log
