#!/bin/bash
#  _               _
# | |__   __ _ ___| |__  _ __ ___
# | '_ \ / _` / __| '_ \| '__/ __|
# | |_) | (_| \__ \ | | | | | (__
# |_.__/ \__,_|___/_| |_|_|  \___|
#
# Set up basic settings.
stty -ixon # Disable ctrl-s and ctrl-q.
shopt -s autocd # Allows you to cd into a directory by only tiping the name.

# Set up vi mode
set -o vi
export EDITOR='vi'
export VISUAL='vi'

# Set up promt and colors.
HISTSIZE= HISTFILESIZE= # Infinite history.
alias ls='ls --color=auto'

# More colors:
export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'

# Configure aliases
source $HOME/.config/aliasrc
export PAGER="most"
export PAGER="less"
